# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='games.proto',
  package='game_kv_store',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgames.proto\x12\rgame_kv_store\"6\n\x04Game\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x10\n\x08platform\x18\x03 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x05\"<\n\x05Value\x12\"\n\x05value\x18\x01 \x01(\x0b\x32\x13.game_kv_store.Game\x12\x0f\n\x07\x64\x65\x66ined\x18\x02 \x01(\x08\":\n\x07NewGame\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.game_kv_store.Game\"\x06\n\x04Void\"\x1a\n\nStoredKeys\x12\x0c\n\x04keys\x18\x01 \x03(\x05\x32\xb6\x01\n\x0bGameService\x12\x31\n\x03get\x12\x12.game_kv_store.Key\x1a\x14.game_kv_store.Value\"\x00\x12\x34\n\x03put\x12\x16.game_kv_store.NewGame\x1a\x13.game_kv_store.Void\"\x00\x12>\n\ngetAllKeys\x12\x13.game_kv_store.Void\x1a\x19.game_kv_store.StoredKeys\"\x00\x62\x06proto3'
)




_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='game_kv_store.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='game_kv_store.Game.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='game_kv_store.Game.price', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='game_kv_store.Game.platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=84,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='game_kv_store.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='game_kv_store.Key.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=104,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='game_kv_store.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='game_kv_store.Value.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defined', full_name='game_kv_store.Value.defined', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=166,
)


_NEWGAME = _descriptor.Descriptor(
  name='NewGame',
  full_name='game_kv_store.NewGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='game_kv_store.NewGame.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='game_kv_store.NewGame.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=226,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='game_kv_store.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=234,
)


_STOREDKEYS = _descriptor.Descriptor(
  name='StoredKeys',
  full_name='game_kv_store.StoredKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='game_kv_store.StoredKeys.keys', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=262,
)

_VALUE.fields_by_name['value'].message_type = _GAME
_NEWGAME.fields_by_name['value'].message_type = _GAME
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['NewGame'] = _NEWGAME
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['StoredKeys'] = _STOREDKEYS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.Game)
  })
_sym_db.RegisterMessage(Game)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.Key)
  })
_sym_db.RegisterMessage(Key)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.Value)
  })
_sym_db.RegisterMessage(Value)

NewGame = _reflection.GeneratedProtocolMessageType('NewGame', (_message.Message,), {
  'DESCRIPTOR' : _NEWGAME,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.NewGame)
  })
_sym_db.RegisterMessage(NewGame)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.Void)
  })
_sym_db.RegisterMessage(Void)

StoredKeys = _reflection.GeneratedProtocolMessageType('StoredKeys', (_message.Message,), {
  'DESCRIPTOR' : _STOREDKEYS,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:game_kv_store.StoredKeys)
  })
_sym_db.RegisterMessage(StoredKeys)



_GAMESERVICE = _descriptor.ServiceDescriptor(
  name='GameService',
  full_name='game_kv_store.GameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=265,
  serialized_end=447,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='game_kv_store.GameService.get',
    index=0,
    containing_service=None,
    input_type=_KEY,
    output_type=_VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='put',
    full_name='game_kv_store.GameService.put',
    index=1,
    containing_service=None,
    input_type=_NEWGAME,
    output_type=_VOID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAllKeys',
    full_name='game_kv_store.GameService.getAllKeys',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_STOREDKEYS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVICE)

DESCRIPTOR.services_by_name['GameService'] = _GAMESERVICE

# @@protoc_insertion_point(module_scope)
